"""Cross-cutting outputs generated by scanning all published posts.

Generates two artifacts at the repo root:
  - staticwebapp.config.json (Azure routing rules — post URLs, redirects,
    blockers for private paths, legacy URL redirects)
  - sitemap.xml (SEO sitemap with static pages, blog listing, and post URLs)

Both functions walk publisher/published/ to discover posts; static page
metadata for sitemap.xml comes from pages.py.
"""


import json
import os
from datetime import datetime

import frontmatter

from .config import PUBLISHER_DIR, URL_SCHEME, post_url_path
from .pages import PAGES


def build_routes(repo_root: str) -> None:
    """Generate staticwebapp.config.json with route rules:
    - Block publisher internals from public access
    - For each post, generate rewrite/redirect rules based on url_scheme
    - For each post's legacy_urls, generate redirects to the current canonical
    """
    published_dir = os.path.join(PUBLISHER_DIR, "published")

    routes = []

    # Baseline: block private files and engine internals from public access
    routes.append({
        "route": "/publisher/*",
        "redirect": "/",
        "statusCode": 301,
    })
    routes.append({
        "route": "/.venv/*",
        "redirect": "/",
        "statusCode": 301,
    })
    routes.append({
        "route": "/requirements.txt",
        "redirect": "/",
        "statusCode": 301,
    })

    if os.path.exists(published_dir):
        for year_dir in sorted(os.listdir(published_dir)):
            year_path = os.path.join(published_dir, year_dir)
            if not os.path.isdir(year_path):
                continue
            for month_dir in sorted(os.listdir(year_path)):
                month_path = os.path.join(year_path, month_dir)
                if not os.path.isdir(month_path):
                    continue
                for filename in sorted(os.listdir(month_path)):
                    if not filename.endswith(".md"):
                        continue
                    md_path = os.path.join(month_path, filename)
                    with open(md_path, "r") as f:
                        post = frontmatter.load(f)

                    post_date = post.get("date")
                    if not post_date:
                        continue

                    if isinstance(post_date, str):
                        date_obj = datetime.strptime(post_date, "%Y-%m-%d")
                    else:
                        date_obj = datetime.combine(post_date, datetime.min.time())

                    date_path = date_obj.strftime("%Y/%m/%d")
                    slug = post.get("slug")
                    if not slug:
                        continue

                    canonical = post_url_path(slug, date_path)
                    physical = f"/blog/{date_path}/{slug}/"
                    physical_file = f"/blog/{date_path}/{slug}/index.html"

                    if URL_SCHEME == "collapsed":
                        # Rewrite the canonical URL to the physical file
                        routes.append({
                            "route": canonical,
                            "rewrite": physical_file,
                        })
                        # Redirect the physical URL to the canonical URL
                        routes.append({
                            "route": physical,
                            "redirect": canonical,
                            "statusCode": 301,
                        })
                    # expanded: canonical == physical, no extra routes needed

                    # Legacy URL redirects (skip self-references and already-handled paths)
                    legacy_urls = post.get("legacy_urls", []) or []
                    for legacy_url in legacy_urls:
                        if legacy_url == canonical:
                            continue
                        if URL_SCHEME == "collapsed" and legacy_url == physical:
                            continue  # already redirected above
                        routes.append({
                            "route": legacy_url,
                            "redirect": canonical,
                            "statusCode": 301,
                        })

    config = {
        "routes": routes,
        "responseOverrides": {
            "404": {
                "redirect": "/",
                "statusCode": 302,
            }
        }
    }

    config_path = os.path.join(repo_root, "staticwebapp.config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    print(f"Wrote: {config_path}")
    print(f"Built routes: {len(routes)} rules")


def build_sitemap(repo_root: str) -> None:
    """Generate sitemap.xml at repo root.
    Static pages come from pages.py; post URLs come from scanning published
    posts using the current url_scheme's canonical form. /blog/'s lastmod is
    computed from the latest post date.
    """
    published_dir = os.path.join(PUBLISHER_DIR, "published")

    base_url = "https://stephenoravec.com"

    post_entries = []
    latest_post_date = None

    if os.path.exists(published_dir):
        for year_dir in sorted(os.listdir(published_dir)):
            year_path = os.path.join(published_dir, year_dir)
            if not os.path.isdir(year_path):
                continue
            for month_dir in sorted(os.listdir(year_path)):
                month_path = os.path.join(year_path, month_dir)
                if not os.path.isdir(month_path):
                    continue
                for filename in sorted(os.listdir(month_path)):
                    if not filename.endswith(".md"):
                        continue
                    md_path = os.path.join(month_path, filename)
                    with open(md_path, "r") as f:
                        post = frontmatter.load(f)

                    post_date = post.get("date")
                    if not post_date:
                        continue

                    if isinstance(post_date, str):
                        date_obj = datetime.strptime(post_date, "%Y-%m-%d")
                    else:
                        date_obj = datetime.combine(post_date, datetime.min.time())

                    date_str = date_obj.strftime("%Y-%m-%d")
                    date_path = date_obj.strftime("%Y/%m/%d")

                    slug = post.get("slug")
                    if not slug:
                        continue

                    canonical = post_url_path(slug, date_path)
                    post_entries.append({
                        "url": canonical,
                        "lastmod": date_str,
                        "priority": "0.6",
                    })

                    if latest_post_date is None or date_str > latest_post_date:
                        latest_post_date = date_str

    # /blog/ entry: lastmod tracks the latest post date
    blog_listing_lastmod = latest_post_date or datetime.now().strftime("%Y-%m-%d")
    blog_listing_entry = {
        "url": "/blog/",
        "lastmod": blog_listing_lastmod,
        "priority": "0.8",
    }

    all_entries = PAGES + [blog_listing_entry] + post_entries

    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')

    for entry in all_entries:
        full_url = f"{base_url}{entry['url']}"
        lines.append("  <url>")
        lines.append(f"    <loc>{full_url}</loc>")
        lines.append(f"    <lastmod>{entry['lastmod']}</lastmod>")
        lines.append(f"    <priority>{entry['priority']}</priority>")
        lines.append("  </url>")

    lines.append('</urlset>')

    sitemap_path = os.path.join(repo_root, "sitemap.xml")
    with open(sitemap_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote: {sitemap_path}")
    print(f"Built sitemap: {len(all_entries)} URLs")